[tox]
envlist = py

[testenv]
cov_args=--cov=mako --cov-report term --cov-report xml

deps=pytest>8
     beaker
     markupsafe
     pygments
     babel
     dogpile.cache
     lingua<4
     cov: pytest-cov

setenv=
    cov: COVERAGE={[testenv]cov_args}

commands=pytest {env:COVERAGE:} {posargs}


[testenv:pep8]
basepython = python3
deps=
      flake8-pyproject
      flake8>=7.3.0
      flake8-import-order>=0.19.2
      flake8-import-single==0.1.5
      flake8-builtins
      flake8-docstrings
      flake8-rst-docstrings
      pydocstyle
      # used by flake8-rst-docstrings
      pygments
      black==26.3.1
commands =
    flake8p ./mako/ ./test/ ./examples/ setup.py --exclude test/templates,test/foo  {posargs}
    black --check .

[testenv:pep484]
basepython = python3
deps=
commands = python -c "print('pep484 is not yet implemented for this project')"
