name: Run tests on a pr

on:
  # run on pull request to main excluding changes that are only on doc or example folders
  pull_request:
    branches:
      - main
    paths-ignore:
      - "doc/**"

jobs:
  run-test:
    name: ${{ matrix.python-version }}-${{ matrix.os }}-${{matrix.nox-session}}
    runs-on: ${{ matrix.os }}
    strategy:
      # run this job using this matrix
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - "3.14"
        nox-session:
          - "-t py-tests"
          - "-s pep8"

      fail-fast: false

    # steps to run in each job. Some are github actions, others run shell commands
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
          pip list

      - name: Run tests
        run: nox ${{ matrix.nox-session }}
