name: Run tests on a pr

on:
  # run on pull request to master excluding changes that are only on doc or example folders
  pull_request:
    branches:
      - master
    paths-ignore:
      - "doc/**"

jobs:
  run-test:
    name: ${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # run this job using this matrix
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - "3.9"

      fail-fast: false

    # steps to run in each job. Some are github actions, others run shell commands
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox setuptools
          pip list

      - name: Run tests
        run: tox