name: Run tests on a pr

on:
  # run on pull request to main excluding changes that are only on doc or example folders
  pull_request:
    branches:
      - main
    paths-ignore:
      - "doc/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
      - name: Test Project linting
        run: |
          pre-commit run --all-files